title: 내 블로그 홈

collections:
  quizzes:
    output: true
    permalink: /quizzes/:path/ # JavaScript에서 fetch하는 경로와 일치시키기 위함

giscus:
  repo: "randomwalk1225/randomwalk1225.github.io"
  repo_id: "R_kgDOOnFjsw"
  category: "Announcements"
  category_id: "DIC_kwDOOnFjs84Cp_iQ"
  mapping: "pathname"
  reactions_enabled: "1" # '좋아요' 같은 반응 기능 사용 (1: 사용, 0: 미사용)
  emit_metadata: "0" # 댓글 작성자 메타데이터 전송 여부 (0: 미사용)
  input_position: "bottom" # 댓글 입력창 위치 (top 또는 bottom)
  theme: "preferred_color_scheme" # 테마 (preferred_color_scheme, light, dark 등)
  lang: "ko" # 언어 설정

# disqus_shortname: "YOUR_DISQUS_SHORTNAME_HERE" # Disqus에서 발급받은 shortname으로 변경하세요.
