# _config.yml

# This is a test comment to trigger a new GitHub Pages build.

markdown: kramdown

kramdown:
  input: GFM               # GitHub-flavored Markdown 지원
  math_engine: mathjax     # MathJax 엔진 사용
  hard_wrap: false

# Explicitly tell Jekyll to use index.md as the main index file
index_files: ['index.md']

baseurl: "" # the subpath of your site, e.g. /blog
